#!/usr/bin/env python

from sh import git, ErrorReturnCode
import sys
import grabber
import maker

try:
    #rename raw_input to input in Python 2
    input = raw_input
except:
    #if raw_input doesn't exist, we're on 3 and fine
    pass

def show_help():
    print('Usage: %s [command]')
    print('Commands:')
    print('init\t\t-- initialize the repository')
    print('update\t\t-- update after component of data.yaml change')
    print('cancel\t\t-- cancel an in-progress update')
    print('commit\t\t-- commit and push an in-progress update')

def init():
    url = input('Remote repository url: ')
    git.remote('set-url', 'origin', url)
    print('Clearing repository history')
    git('update-ref', '-d', 'refs/heads/master')
    git.commit('-s', '-m', 'Initial import')
    print('Pushing master to remote')
    git.push('-u', 'origin', 'master')
    git.checkout('-b', 'run-codegen')
    print('Pushing run-codegen to remote')
    git.push('-u', 'origin', 'run-codegen')
    git.checkout('master')

def cancel():
    git.reset('--hard')
    git.checkout('run-codegen')
    git.reset('--hard', 'origin/run-codegen')
    git.checkout('master')

def commit():
    git.commit(message='merged run-codegen')
    print('pushing new master')
    git.push()
    git.checkout('run-codegen')
    print('pushing new run-codegen')
    git.push()
    git.checkout('master')

def update():
    try:
        git.show('master:data.yaml', _tty_out=False)
    except ErrorReturnCode:
        print('Error: data.yaml not committed to master')
        sys.exit(1)
    grabber.grab_components()
    git.checkout('run-codegen')
    git.checkout('master', '--', 'data.yaml')

    maker.make_all()
    print('Committing changes to run-codegen')
    git.add('-A')
    git.commit(message='codegen rerun')
    git.checkout('master')
    print('Merging changes into master')
    git.merge('run-codegen', '--no-commit', '--no-ff')
    print('Merge complete.')
    print('Review changes, edit and git-add as needed')
    print("Run `./hatch commit` when you're happy with the changes.")
    print('Run `./hatch cancel` if you want to cancel the update.')

if __name__ == '__main__':
    if len(sys.argv) < 2:
        show_help()
    elif sys.argv[1] == 'init':
        init()
    elif sys.argv[1] == 'update':
        update()
    elif sys.argv[1] == 'cancel':
        cancel()
    elif sys.argv[1] == 'commit':
        commit()
    else:
        show_help()

